# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  image: latest
  apt_packages:
    - ffmpeg

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
