# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - ffmpeg

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
