// Definitions taken from config.h
// Hack - todo: see if this should be part of dune lib installation?
#define HAVE_DUNE_TYPETREE 1
#define HAVE_DUNE_GRID 1
#define HAVE_DUNE_UGGRID 1
#define HAVE_DUNE_ALUGRID 0
#define HAVE_DUNE_MULTIDOMAINGRID 1
#define HAVE_DUNE_FUNCTIONS 1

#define HAVE_DUNE_COPASI 1
#define HAVE_DUNE_COMMON 1
#define HAVE_DUNE_GEOMETRY 1
#define HAVE_DUNE_ISTL 1
#define HAVE_DUNE_LOCALFUNCTIONS 1
#define HAVE_DUNE_TESTTOOLS 0
#define HAVE_DUNE_PDELAB 1
#define HAVE_DUNE_LOGGING 1

#define DUNE_COMMON_VERSION_MAJOR 2
#define DUNE_COMMON_VERSION_MINOR 7
#define DUNE_COMMON_VERSION_REVISION 0

#define DUNE_MINIMAL_DEBUG_LEVEL 4
#define HAS_ATTRIBUTE_DEPRECATED 1
#define HAS_ATTRIBUTE_DEPRECATED_MSG 1
#define HAS_ATTRIBUTE_UNUSED 1
#define DUNE_HAVE_CXX_CLASS_TEMPLATE_ARGUMENT_DEDUCTION 1
#define DUNE_HAVE_CXX_OPTIONAL 1
#define DUNE_HAVE_CXX_VARIANT 1
#define DUNE_SUPPORTS_CXX_THROW_IN_CONSTEXPR 1
#define DUNE_HAVE_HEADER_EXPERIMENTAL_TYPE_TRAITS 1
#define DUNE_HAVE_CXX_BOOL_CONSTANT 1
#define DUNE_HAVE_CXX_APPLY 1
#define DUNE_HAVE_CXX_EXPERIMENTAL_MAKE_ARRAY 1
#define DUNE_HAVE_CXX_EXPERIMENTAL_IS_DETECTED 1
#define HAVE_CXA_DEMANGLE 1
#define HAVE_GMP ENABLE_GMP
#define HAVE_MPROTECT 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_IS_INDEXABLE_SUPPORT 1

#define DUNE_UGGRID_VERSION_MAJOR 2
#define DUNE_UGGRID_VERSION_MINOR 7
#define DUNE_UGGRID_VERSION_REVISION 0

#ifndef HAVE_RPC_RPC_H
#define HAVE_RPC_RPC_H 1
#endif

#define DUNE_GEOMETRY_VERSION_MAJOR 2
#define DUNE_GEOMETRY_VERSION_MINOR 7
#define DUNE_GEOMETRY_VERSION_REVISION 0

#define DUNE_TYPETREE_VERSION_MAJOR 2
#define DUNE_TYPETREE_VERSION_MINOR 7
#define DUNE_TYPETREE_VERSION_REVISION 0

#define HAVE_MEM_USAGE_T_EXPANSIONS 1

#define DUNE_ISTL_VERSION_MAJOR 2
#define DUNE_ISTL_VERSION_MINOR 7
#define DUNE_ISTL_VERSION_REVISION 0
#define DUNE_ISTL_SUPPORT_OLD_CATEGORY_INTERFACE 1

#define DUNE_GRID_VERSION_MAJOR 2
#define DUNE_GRID_VERSION_MINOR 7
#define DUNE_GRID_VERSION_REVISION 0
#define DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS 1
#define HAVE_UG ENABLE_UG
#define HAVE_MKSTEMP 1

#define DUNE_LOCALFUNCTIONS_VERSION_MAJOR 2
#define DUNE_LOCALFUNCTIONS_VERSION_MINOR 7
#define DUNE_LOCALFUNCTIONS_VERSION_REVISION 0

#define DUNE_FUNCTIONS_VERSION_MAJOR 2
#define DUNE_FUNCTIONS_VERSION_MINOR 7
#define DUNE_FUNCTIONS_VERSION_REVISION 0

#define DUNE_MULTIDOMAINGRID_VERSION_MAJOR 2
#define DUNE_MULTIDOMAINGRID_VERSION_MINOR 7
#define DUNE_MULTIDOMAINGRID_VERSION_REVISION 0

#define DUNE_PDELAB_VERSION_MAJOR 2
#define DUNE_PDELAB_VERSION_MINOR 7
#define DUNE_PDELAB_VERSION_REVISION 0

#ifndef DUNE_MAX_LOGLEVEL
#define DUNE_MAX_LOGLEVEL all
#endif

#define DUNE_HAVE_LOCALTIME_R
