name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  quality:
    name: ${{ matrix.script }}
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        script: [codecov, asan, ubsan]
    steps:
      - uses: spatial-model-editor/setup-ci@2026.03.30
        with:
          sme_deps: '2026.04.30'
          cache_id: ${{ matrix.script }}
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 0
